## 1) Importing Libraries

In [1]:
# here to import needed libaries which will be used in our project
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

## 2) Data 

In [2]:
#ls

In [3]:
data = pd.read_excel('Data_Train.xlsx')
test = pd.read_excel('Test_set.xlsx')

In [4]:
data.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

In [5]:
print(f'there are {data.shape[0]} row and {data.shape[1]} columns in our training set')

there are 10683 row and 11 columns in our training set


In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64 
dtypes: int64(1), object(10)
memory usage: 918.2+ KB


## 3) handling null Values

In [7]:
data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [8]:
data['Route'].isnull().values

array([False, False, False, ..., False, False, False])

In [9]:
# getting the index where null value in it
for index , value in enumerate(data['Route'].isnull().values):
    if value:
        print(f'Null value at index {index}')

Null value at index 9039


In [10]:
data.loc[9039]

Airline               Air India
Date_of_Journey       6/05/2019
Source                    Delhi
Destination              Cochin
Route                       NaN
Dep_Time                  09:45
Arrival_Time       09:25 07 May
Duration                23h 40m
Total_Stops                 NaN
Additional_Info         No info
Price                      7480
Name: 9039, dtype: object

In [11]:
## let's delete null value row
data.drop([9039], axis = 0 , inplace=True)

In [12]:
data.reset_index(inplace=True)
data.drop(['index'],axis=1,inplace=True)

## 4) Data Processing

In [13]:
def show_column_details(col):
    global data
    print(f'for feature {col}')
    print(f'Number of Nulls is {data[col].isna().sum()}')
    print(f'Number of Unique Values is {len(data[col].unique())}')
    print(f'Random Value is {data[col][np.random.randint(data.shape[0])]}')
    print(f'Random Value is {data[col][np.random.randint(data.shape[0])]}')
    print(f'Random Value is {data[col][np.random.randint(data.shape[0])]}')
    print('\n\n==================================\n\n')

In [14]:
show_column_details('Date_of_Journey')

for feature Date_of_Journey
Number of Nulls is 0
Number of Unique Values is 44
Random Value is 15/05/2019
Random Value is 6/03/2019
Random Value is 9/03/2019






In [15]:
# let's extract day , month and year from "date_of_jounry" column
data['DayOfJourny'] = data['Date_of_Journey'].apply(lambda x:x.split('/')[0])
data['MonthOfJourny'] = data['Date_of_Journey'].apply(lambda x:x.split('/')[1])
data['YearOfJourny'] = data['Date_of_Journey'].apply(lambda x:x.split('/')[2])

In [16]:
data.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

  DayOfJourny MonthOfJourny YearOfJourny  
0          24            03         2019  
1           1            05         2019  
2           9            06         2019  
3          12            05         2019  
4          01            03         2019

In [17]:
data['DayOfJourny'].unique()

array(['24', '1', '9', '12', '01', '27', '18', '3', '15', '6', '21', '06',
       '09', '03'], dtype=object)

In [18]:
data['MonthOfJourny'].unique()

array(['03', '05', '06', '04'], dtype=object)

In [19]:
data['YearOfJourny'].unique()

array(['2019'], dtype=object)

In [20]:
# there is only unique value in year column so let's delete it 
data.drop('YearOfJourny',axis = 1 , inplace=True)

In [21]:
data['DayOfJourny'] = data['DayOfJourny'].astype(int)
data['MonthOfJourny'] = data['MonthOfJourny'].astype(int)

In [22]:
data['DayOfJourny'].unique()

array([24,  1,  9, 12, 27, 18,  3, 15,  6, 21])

In [23]:
data['MonthOfJourny'].unique()

array([3, 5, 6, 4])

In [24]:
show_column_details('Arrival_Time')

for feature Arrival_Time
Number of Nulls is 0
Number of Unique Values is 1343
Random Value is 04:25 04 Jun
Random Value is 10:15
Random Value is 23:40






In [25]:
data['AccurateArrivalTime'] = data['Arrival_Time'].apply(lambda x : x.split()[0])

In [26]:
data['AccurateArrivalTime'].head()

0    01:10
1    13:15
2    04:25
3    23:30
4    21:35
Name: AccurateArrivalTime, dtype: object

In [28]:
data.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   DayOfJourny  MonthOfJourny AccurateArrivalTime  
0           24              3               01:10  
1            1              5               13:15  
2            9              6               04:25  
3           12              5               23:30  
4            1              3               21:35

In [34]:
data['stopCount'] = data['Route'].apply(lambda x:str(x).count('→') - 1)
data[['stopCount','Total_Stops']].head()

stopCount Total_Stops
0          0    non-stop
1          2     2 stops
2          2     2 stops
3          1      1 stop
4          1      1 stop

In [35]:
data['Total_Stops'].value_counts()

1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: Total_Stops, dtype: int64

In [36]:
data['stopCount'].value_counts()

1    5625
0    3491
2    1520
3      45
4       1
Name: stopCount, dtype: int64